
export const religion = [
    {
        label: "Islam",
    }, 
    {
        label: "Christianity"
    }, 
    {
        label: "Hinduism"
    },
    {
        label: "Buddhism"
    },
    {
        label: "Folk"
    },{
        label: "Atheist"
    },

]





export const skinTone = [
    {
        label: "White",
    }, 
    {
        label: "Brown"
    }, 
    {
        label: "Black"
    }
]


export const continent = [
    {
        label: "Asia",
    }, 
    {
        label: "Africa"
    }, 
    {
        label: "Europe"
    },    
    {
        label: "North America"
    },
    {
        label: "South America"
    },
    {
        label: "Australia"
    },
    {
        label: "Antarctica"
    }
]



// chinese 
// Amarican
// Middle este
// Indian
// African


export const ethnicList = [
    {
        label: "Chinese"
    },
    {
        label: "American"
    },
    {
        label: "Middle Eastern"
    },
    {
        label: "Indian"
    },
    {
        label: "African"
    },{
        label:"Others"
    }
];




export const countryName = [
    { id: 1, label: "Afghanistan", flag: "af" },
    { id: 2, label: "Albania", flag: "al" },
    { id: 3, label: "Algeria", flag: "dz" },
    { id: 4, label: "Andorra", flag: "ad" },
    { id: 5, label: "Angola", flag: "ao" },
    { id: 6, label: "Antigua and Barbuda", flag: "ag" },
    { id: 7, label: "Argentina", flag: "ar" },
    { id: 8, label: "Armenia", flag: "am" },
    { id: 9, label: "Australia", flag: "au" },
    { id: 10, label: "Austria", flag: "at" },
    { id: 11, label: "Azerbaijan", flag: "az" },
    { id: 12, label: "Bahamas", flag: "bs" },
    { id: 13, label: "Bahrain", flag: "bh" },
    { id: 14, label: "Bangladesh", flag: "bd" },
    { id: 15, label: "Barbados", flag: "bb" },
    { id: 16, label: "Belarus", flag: "by" },
    { id: 17, label: "Belgium", flag: "be" },
    { id: 18, label: "Belize", flag: "bz" },
    { id: 19, label: "Benin", flag: "bj" },
    { id: 20, label: "Bhutan", flag: "bt" },
    { id: 21, label: "Bolivia", flag: "bo" },
    { id: 22, label: "Bosnia and Herzegovina", flag: "ba" },
    { id: 23, label: "Botswana", flag: "bw" },
    { id: 24, label: "Brazil", flag: "br" },
    { id: 25, label: "Brunei", flag: "bn" },
    { id: 26, label: "Bulgaria", flag: "bg" },
    { id: 27, label: "Burkina Faso", flag: "bf" },
    { id: 28, label: "Burundi", flag: "bi" },
    { id: 29, label: "Cabo Verde", flag: "cv" },
    { id: 30, label: "Cambodia", flag: "kh" },
    { id: 31, label: "Cameroon", flag: "cm" },
    { id: 32, label: "Canada", flag: "ca" },
    { id: 33, label: "Central African Republic", flag: "cf" },
    { id: 34, label: "Chad", flag: "td" },
    { id: 35, label: "Chile", flag: "cl" },
    { id: 36, label: "China", flag: "cn" },
    { id: 37, label: "Colombia", flag: "co" },
    { id: 38, label: "Comoros", flag: "km" },
    { id: 39, label: "Congo, Democratic Republic of the", flag: "cd" },
    { id: 40, label: "Congo, Republic of the", flag: "cg" },
    { id: 41, label: "Costa Rica", flag: "cr" },
    { id: 42, label: "Croatia", flag: "hr" },
    { id: 43, label: "Cuba", flag: "cu" },
    { id: 44, label: "Cyprus", flag: "cy" },
    { id: 45, label: "Czech Republic", flag: "cz" },
    { id: 46, label: "Denmark", flag: "dk" },
    { id: 47, label: "Djibouti", flag: "dj" },
    { id: 48, label: "Dominica", flag: "dm" },
    { id: 49, label: "Dominican Republic", flag: "do" },
    { id: 50, label: "East Timor (Timor-Leste)", flag: "tl" },
    { id: 51, label: "Ecuador", flag: "ec" },
    { id: 52, label: "Egypt", flag: "eg" },
    { id: 53, label: "El Salvador", flag: "sv" },
    { id: 54, label: "Equatorial Guinea", flag: "gq" },
    { id: 55, label: "Eritrea", flag: "er" },
    { id: 56, label: "Estonia", flag: "ee" },
    { id: 57, label: "Eswatini", flag: "sz" },
    { id: 58, label: "Ethiopia", flag: "et" },
    { id: 59, label: "Fiji", flag: "fj" },
    { id: 60, label: "Finland", flag: "fi" },
    { id: 61, label: "France", flag: "fr" },
    { id: 62, label: "Gabon", flag: "ga" },
    { id: 63, label: "Gambia", flag: "gm" },
    { id: 64, label: "Georgia", flag: "ge" },
    { id: 65, label: "Germany", flag: "de" },
    { id: 66, label: "Ghana", flag: "gh" },
    { id: 67, label: "Greece", flag: "gr" },
    { id: 68, label: "Grenada", flag: "gd" },
    { id: 69, label: "Guatemala", flag: "gt" },
    { id: 70, label: "Guinea", flag: "gn" },
    { id: 71, label: "Guinea-Bissau", flag: "gw" },
    { id: 72, label: "Guyana", flag: "gy" },
    { id: 73, label: "Haiti", flag: "ht" },
    { id: 74, label: "Honduras", flag: "hn" },
    { id: 75, label: "Hungary", flag: "hu" },
    { id: 76, label: "Iceland", flag: "is" },
    { id: 77, label: "India", flag: "in" },
    { id: 78, label: "Indonesia", flag: "id" },
    { id: 79, label: "Iran", flag: "ir" },
    { id: 80, label: "Iraq", flag: "iq" },
    { id: 81, label: "Ireland", flag: "ie" },
    { id: 82, label: "Israel", flag: "il" },
    { id: 83, label: "Italy", flag: "it" },
    { id: 84, label: "Jamaica", flag: "jm" },
    { id: 85, label: "Japan", flag: "jp" },
    { id: 86, label: "Jordan", flag: "jo" },
    { id: 87, label: "Kazakhstan", flag: "kz" },
    { id: 88, label: "Kenya", flag: "ke" },
    { id: 89, label: "Kiribati", flag: "ki" },
    { id: 90, label: "Korea, North", flag: "kp" },
    { id: 91, label: "Korea, South", flag: "kr" },
    { id: 92, label: "Kosovo", flag: "xk" },
    { id: 93, label: "Kuwait", flag: "kw" },
    { id: 94, label: "Kyrgyzstan", flag: "kg" },
    { id: 95, label: "Laos", flag: "la" },
    { id: 96, label: "Latvia", flag: "lv" },
    { id: 97, label: "Lebanon", flag: "lb" },
    { id: 98, label: "Lesotho", flag: "ls" },
    { id: 99, label: "Liberia", flag: "lr" },
    { id: 100, label: "Libya", flag: "ly" },
    { id: 101, label: "Liechtenstein", flag: "li" },
    { id: 102, label: "Lithuania", flag: "lt" },
    { id: 103, label: "Luxembourg", flag: "lu" },
    { id: 104, label: "Madagascar", flag: "mg"

 },
    { id: 105, label: "Malawi", flag: "mw" },
    { id: 106, label: "Malaysia", flag: "my" },
    { id: 107, label: "Maldives", flag: "mv" },
    { id: 108, label: "Mali", flag: "ml" },
    { id: 109, label: "Malta", flag: "mt" },
    { id: 110, label: "Marshall Islands", flag: "mh" },
    { id: 111, label: "Mauritania", flag: "mr" },
    { id: 112, label: "Mauritius", flag: "mu" },
    { id: 113, label: "Mexico", flag: "mx" },
    { id: 114, label: "Micronesia", flag: "fm" },
    { id: 115, label: "Moldova", flag: "md" },
    { id: 116, label: "Monaco", flag: "mc" },
    { id: 117, label: "Mongolia", flag: "mn" },
    { id: 118, label: "Montenegro", flag: "me" },
    { id: 119, label: "Morocco", flag: "ma" },
    { id: 120, label: "Mozambique", flag: "mz" },
    { id: 121, label: "Myanmar", flag: "mm" },
    { id: 122, label: "Namibia", flag: "na" },
    { id: 123, label: "Nauru", flag: "nr" },
    { id: 124, label: "Nepal", flag: "np" },
    { id: 125, label: "Netherlands", flag: "nl" },
    { id: 126, label: "New Zealand", flag: "nz" },
    { id: 127, label: "Nicaragua", flag: "ni" },
    { id: 128, label: "Niger", flag: "ne" },
    { id: 129, label: "Nigeria", flag: "ng" },
    { id: 130, label: "North Macedonia", flag: "mk" },
    { id: 131, label: "Norway", flag: "no" },
    { id: 132, label: "Oman", flag: "om" },
    { id: 133, label: "Pakistan", flag: "pk" },
    { id: 134, label: "Palau", flag: "pw" },
    { id: 135, label: "Panama", flag: "pa" },
    { id: 136, label: "Papua New Guinea", flag: "pg" },
    { id: 137, label: "Paraguay", flag: "py" },
    { id: 138, label: "Peru", flag: "pe" },
    { id: 139, label: "Philippines", flag: "ph" },
    { id: 140, label: "Poland", flag: "pl" },
    { id: 141, label: "Portugal", flag: "pt" },
    { id: 142, label: "Qatar", flag: "qa" },
    { id: 143, label: "Romania", flag: "ro" },
    { id: 144, label: "Russia", flag: "ru" },
    { id: 145, label: "Rwanda", flag: "rw" },
    { id: 146, label: "Saint Kitts and Nevis", flag: "kn" },
    { id: 147, label: "Saint Lucia", flag: "lc" },
    { id: 148, label: "Saint Vincent and the Grenadines", flag: "vc" },
    { id: 149, label: "Samoa", flag: "ws" },
    { id: 150, label: "San Marino", flag: "sm" },
    { id: 151, label: "Sao Tome and Principe", flag: "st" },
    { id: 152, label: "Saudi Arabia", flag: "sa" },
    { id: 153, label: "Senegal", flag: "sn" },
    { id: 154, label: "Serbia", flag: "rs" },
    { id: 155, label: "Seychelles", flag: "sc" },
    { id: 156, label: "Sierra Leone", flag: "sl" },
    { id: 157, label: "Singapore", flag: "sg" },
    { id: 158, label: "Slovakia", flag: "sk" },
    { id: 159, label: "Slovenia", flag: "si" },
    { id: 160, label: "Solomon Islands", flag: "sb" },
    { id: 161, label: "Somalia", flag: "so" },
    { id: 162, label: "South Africa", flag: "za" },
    { id: 163, label: "South Sudan", flag: "ss" },
    { id: 164, label: "Spain", flag: "es" },
    { id: 165, label: "Sri Lanka", flag: "lk" },
    { id: 166, label: "Sudan", flag: "sd" },
    { id: 167, label: "Suriname", flag: "sr" },
    { id: 168, label: "Sweden", flag: "se" },
    { id: 169, label: "Switzerland", flag: "ch" },
    { id: 170, label: "Syria", flag: "sy" },
    { id: 171, label: "Taiwan", flag: "tw" },
    { id: 172, label: "Tajikistan", flag: "tj" },
    { id: 173, label: "Tanzania", flag: "tz" },
    { id: 174, label: "Thailand", flag: "th" },
    { id: 175, label: "Togo", flag: "tg" },
    { id: 176, label: "Tonga", flag: "to" },
    { id: 177, label: "Trinidad and Tobago", flag: "tt" },
    { id: 178, label: "Tunisia", flag: "tn" },
    { id: 179, label: "Turkey", flag: "tr" },
    { id: 180, label: "Turkmenistan", flag: "tm" },
    { id: 181, label: "Tuvalu", flag: "tv" },
    { id: 182, label: "Uganda", flag: "ug" },
    { id: 183, label: "Ukraine", flag: "ua" },
    { id: 184, label: "United Arab Emirates", flag: "ae" },
    { id: 185, label: "United Kingdom", flag: "gb" },
    { id: 186, label: "United States", flag: "us" },
    { id: 187, label: "Uruguay", flag: "uy" },
    { id: 188, label: "Uzbekistan", flag: "uz" },
    { id: 189, label: "Vanuatu", flag: "vu" },
    { id: 190, label: "Vatican City", flag: "va" },
    { id: 191, label: "Venezuela", flag: "ve" },
    { id: 192, label: "Vietnam", flag: "vn" },
    { id: 193, label: "Yemen", flag: "ye" },
    { id: 194, label: "Zambia", flag: "zm" },
    { id: 195, label: "Zimbabwe", flag: "zw" }
];





export const languageList = [
    { id: 1, label: "Abkhaz" },
    { id: 2, label: "Afar" },
    { id: 3, label: "Afrikaans" },
    { id: 4, label: "Akan" },
    { id: 5, label: "Albanian" },
    { id: 6, label: "Amharic" },
    { id: 7, label: "Arabic" },
    { id: 8, label: "Aragonese" },
    { id: 9, label: "Armenian" },
    { id: 10, label: "Assamese" },
    { id: 11, label: "Avaric" },
    { id: 12, label: "Avestan" },
    { id: 13, label: "Aymara" },
    { id: 14, label: "Azerbaijani" },
    { id: 15, label: "Bambara" },
    { id: 16, label: "Bashkir" },
    { id: 17, label: "Basque" },
    { id: 18, label: "Belarusian" },
    { id: 19, label: "Bengali" },
    { id: 20, label: "Bihari" },
    { id: 21, label: "Bislama" },
    { id: 22, label: "Bosnian" },
    { id: 23, label: "Breton" },
    { id: 24, label: "Bulgarian" },
    { id: 25, label: "Burmese" },
    { id: 26, label: "Catalan" },
    { id: 27, label: "Chamorro" },
    { id: 28, label: "Chechen" },
    { id: 29, label: "Chichewa" },
    { id: 30, label: "Chinese" },
    { id: 31, label: "Chuvash" },
    { id: 32, label: "Cornish" },
    { id: 33, label: "Corsican" },
    { id: 34, label: "Cree" },
    { id: 35, label: "Croatian" },
    { id: 36, label: "Czech" },
    { id: 37, label: "Danish" },
    { id: 38, label: "Divehi" },
    { id: 39, label: "Dutch" },
    { id: 40, label: "Dzongkha" },
    { id: 41, label: "English" },
    { id: 42, label: "Esperanto" },
    { id: 43, label: "Estonian" },
    { id: 44, label: "Ewe" },
    { id: 45, label: "Faroese" },
    { id: 46, label: "Fijian" },
    { id: 47, label: "Finnish" },
    { id: 48, label: "French" },
    { id: 49, label: "Fula" },
    { id: 50, label: "Galician" },
    { id: 51, label: "Georgian" },
    { id: 52, label: "German" },
    { id: 53, label: "Greek" },
    { id: 54, label: "Guarani" },
    { id: 55, label: "Gujarati" },
    { id: 56, label: "Haitian" },
    { id: 57, label: "Hausa" },
    { id: 58, label: "Hebrew" },
    { id: 59, label: "Herero" },
    { id: 60, label: "Hindi" },
    { id: 61, label: "Hiri Motu" },
    { id: 62, label: "Hungarian" },
    { id: 63, label: "Interlingua" },
    { id: 64, label: "Indonesian" },
    { id: 65, label: "Interlingue" },
    { id: 66, label: "Irish" },
    { id: 67, label: "Igbo" },
    { id: 68, label: "Inupiaq" },
    { id: 69, label: "Ido" },
    { id: 70, label: "Icelandic" },
    { id: 71, label: "Italian" },
    { id: 72, label: "Inuktitut" },
    { id: 73, label: "Japanese" },
    { id: 74, label: "Javanese" },
    { id: 75, label: "Kalaallisut" },
    { id: 76, label: "Kannada" },
    { id: 77, label: "Kanuri" },
    { id: 78, label: "Kashmiri" },
    { id: 79, label: "Kazakh" },
    { id: 80, label: "Khmer" },
    { id: 81, label: "Kikuyu" },
    { id: 82, label: "Kinyarwanda" },
    { id: 83, label: "Kirundi" },
    { id: 84, label: "Komi" },
    { id: 85, label: "Kongo" },
    { id: 86, label: "Korean" },
    { id: 87, label: "Kurdish" },
    { id: 88, label: "Kwanyama" },
    { id: 89, label: "Latin" },
    { id: 90, label: "Luxembourgish" },
    { id: 91, label: "Luganda" },
    { id: 92, label: "Limburgish" },
    { id: 93, label: "Lingala" },
    { id: 94, label: "Lao" },
    { id: 95, label: "Lithuanian" },
    { id: 96, label: "Luba-Katanga" },
    { id: 97, label: "Latvian" },
    { id: 98, label: "Manx" },
    { id: 99, label: "Macedonian" },
    { id: 100, label: "Malagasy" },
    { id: 101, label: "Malay" },
    { id: 102, label: "Malayalam" },
    { id: 103, label: "Maltese" },
    { id: 104, label: "Maori" },
    { id: 105, label: "Marathi" },
    { id: 106, label: "Marshallese" },
    { id: 107, label: "Mongolian" },
    { id: 108, label: "Nauru" },
    { id: 109, label: "Navajo" },
    { id: 110, label: "Norwegian Bokmål" },
    { id: 111, label: "North Ndebele" },
    { id: 112, label: "Nepali" },
    { id: 113, label: "Ndonga" },
    { id: 114, label: "Norwegian Nynorsk" },
    { id: 115, label: "Norwegian" },
    { id: 116, label: "Nuosu" },
    { id: 117, label: "South Ndebele" },
    { id: 118, label: "Occitan" },
    { id: 119, label: "Ojibwe" },
    { id: 120, label: "Old Church Slavonic" },
    { id: 121, label: "Oromo" },
    { id: 122, label: "Oriya" },
    { id: 123, label: "Ossetian" },
    { id: 124, label: "Panjabi" },
    { id: 125, label: "Pāli" },
    { id: 126, label: "Persian" },
    { id: 127, label: "Polish" },
    { id: 128, label: "Pashto" },
    { id: 129, label: "Portuguese" },
    { id: 130, label: "Quechua" },
    { id: 131, label: "Romansh" },
    { id: 132, label: "Kirundi" },
    { id: 133, label: "Romanian" },
    { id: 134, label: "Russian" },
    { id: 135, label: "Sanskrit" },
    { id: 136, label: "Sardinian" },
    { id: 137, label: "Sindhi" },
    { id: 138, label: "Northern Sami" },
    { id: 139, label: "Samoan" },
    { id: 140, label: "Sango"

 },
    { id: 141, label: "Serbian" },
    { id: 142, label: "Scottish Gaelic" },
    { id: 143, label: "Shona" },
    { id: 144, label: "Sinhala" },
    { id: 145, label: "Slovak" },
    { id: 146, label: "Slovene" },
    { id: 147, label: "Somali" },
    { id: 148, label: "Southern Sotho" },
    { id: 149, label: "Spanish" },
    { id: 150, label: "Sundanese" },
    { id: 151, label: "Swahili" },
    { id: 152, label: "Swati" },
    { id: 153, label: "Swedish" },
    { id: 154, label: "Tamil" },
    { id: 155, label: "Telugu" },
    { id: 156, label: "Tajik" },
    { id: 157, label: "Thai" },
    { id: 158, label: "Tigrinya" },
    { id: 159, label: "Tibetan" },
    { id: 160, label: "Turkmen" },
    { id: 161, label: "Tagalog" },
    { id: 162, label: "Tswana" },
    { id: 163, label: "Tonga" },
    { id: 164, label: "Turkish" },
    { id: 165, label: "Tsonga" },
    { id: 166, label: "Tatar" },
    { id: 167, label: "Twi" },
    { id: 168, label: "Tahitian" },
    { id: 169, label: "Uighur" },
    { id: 170, label: "Ukrainian" },
    { id: 171, label: "Urdu" },
    { id: 172, label: "Uzbek" },
    { id: 173, label: "Venda" },
    { id: 174, label: "Vietnamese" },
    { id: 175, label: "Volapük" },
    { id: 176, label: "Walloon" },
    { id: 177, label: "Welsh" },
    { id: 178, label: "Wolof" },
    { id: 179, label: "Western Frisian" },
    { id: 180, label: "Xhosa" },
    { id: 181, label: "Yiddish" },
    { id: 182, label: "Yoruba" },
    { id: 183, label: "Zhuang" },
    { id: 184, label: "Zulu" }
];